### PR TITLE
[update Privacy policy]Google uses cookies

### PR DESCRIPTION
**Pull request by I-Cat**
Updated how we learn about people to include information about Google Analytics and how it works and the fact that it can use cookies

## Types of change

- [ maybe ] **Bug fix** (non-breaking change which fixes an issue)
- [ no ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ sure ] **Improvement** (non-breaking change which improves existing functionality)
- [ no ] **New feature** (non-breaking change which adds functionality)
- [ no ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [x] **None of the above** (please explain below)

     Fix Privacy policy  according to Kodi.tv web site.

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated "this" documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ no ] I have added tests to cover my change
- [ it should ] All new and existing tests passed

### CODE REVIEW

**Comment by I-Cat** [comment]
@AlwinEsch AlwinEsch

**Comment by Razzeee** [comment]
I think the source where you copied this from needs updating, google analytics is no longer in use for example (I'm not sure if the wiki might still use it)

Anyway, alwins fork is the wrong place to address this.

**Comment by I-Cat** [comment]
> I think the source where you copied this from needs updating, google analytics is no longer in use for example (I'm not sure if the wiki might still use it)
> 
> Anyway, alwins fork is the wrong place to address this.

@Razzeee Okay How do I Address this please.

**Comment by Razzeee** [comment]
I think best would be to wait for an updated privacy policy version. As I think analytics would best be removed.

**Pull request closed without merging**
