### PR TITLE
[peripheral] Cosmetic: Fix doxy indentation

### PR DESCRIPTION
**Pull request by garbear**
Just a detail I noticed while reviewing #12333

I also discovered Input Stream add-ons had the same doxy problem, so I included that fix too

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Thanks a lot! Was planned from me to go over all addon documentation after the system is complete changed.

**Comment by garbear** [comment]
> Thanks a lot! Was planned from me to go over all addon documentation after the system is complete changed.

Same here. Your comments could use the beautifying touch of a native speaker, so once everything's in I'll help go through and improve our doxy

**Comment by AlwinEsch** [comment]
Thanks a lot, there is planned from me a lot to have a easy usable documentation for binaries.

Here where I start some time ago and what show a bit from them what I want to have: 
 http://alwinesch.github.io/group__cpp__kodi__addon__audiodecoder.html

Need really to improve them a good english speaking man :)

**Comment by garbear** [comment]
Where does the first sentence:

`An audio codec is a add-on capable of coding or decoding a digital data stream of audio.`

come from? I couldn't find that sentence in Kodi's source.

**Comment by AlwinEsch** [comment]
Is from me where I searched and think about small descriptions on start, some parts on docs are not taken from Kodi and complete new.

**Pull request merged**
